"""Codex adapter: global instructions by symlink, the table as Starlark prefix rules, the
pre-tool hook in hooks.json, and memory off in config.toml.

Facts it relies on (see references/codex.md and docs/research/harness-capabilities.md, section 2):
- `~/.codex/AGENTS.md` loads in every session and may be a symlink; it has no imports.
  A non-empty `~/.codex/AGENTS.override.md` is read instead of it.
- Every `~/.codex/rules/*.rules` file loads; `prefix_rule(pattern, decision, justification)`
  matches an argv prefix token by token, an element being one word or a list of
  alternatives. The strictest matching decision wins across files. A `forbidden`
  rule's justification is what the agent reads when it's refused. Codex resolves an
  absolute program path to its basename, so `/bin/rm` needs no rule of its own.
- Codex runs every shell command as `[<shell>, "-lc", <command>]` (`-c` when login is
  off), and matches a rule against that argv when the command isn't a plain chain
  of words, so a rule on `bash -c` or `zsh -lc` would refuse its own wrapper.
- `~/.codex/hooks.json` holds `hooks.PreToolUse` matcher groups like Claude Code's. A
  non-managed hook runs only once trusted: `[hooks.state."<file>:pre_tool_use:<group>:<handler>"]
  trusted_hash` in config.toml, a sha256 of the hook's normalised identity.
- `[features] memories = false` in config.toml keeps local memories off; they're
  written under `~/.codex/memories/`. A trusted project's `.codex/config.toml` can
  turn memories on or hooks off; only a system `requirements.toml` pins them.
"""
from __future__ import annotations

import ast
import hashlib
import itertools
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path

from .. import commands, memory, shared
from .. import rules as rule_table
from ..plan import Change, FileWrite, Run, Section, link_text
from ..shared import read_text
from .claude_code import HOOK_MISSES, hook_command

NAME = "codex"
LABEL = "Codex"
PROGRAMS = ("codex",)  # on PATH, they mark a fresh install whose folder isn't made yet

# Rule level -> the Codex decision that expresses it.
DECISION = {"deny": "forbidden", "ask": "prompt", "allow-and-report": "allow"}
STRICTNESS = {"allow": 0, "prompt": 1, "forbidden": 2}
RULES_FILE = "set-up-machine.rules"
RULES_HEADER = (
    "# Generated by set-up-machine from its rule table: change the table, not this file.\n"
    "# Codex loads every *.rules file here; the strictest matching decision wins.\n"
)
HOOK_TIMEOUT = 10

FEATURE_LINE = "memories = false"
_TABLE = re.compile(r"^\s*\[\s*([^\[\]]+?)\s*\]\s*(#.*)?$")
_MEMORIES = re.compile(r"^\s*memories\s*=\s*(\S+)")
_DOTTED = re.compile(r"^\s*features\s*\.\s*memories\s*=\s*(\S+)")


@dataclass(frozen=True)
class ExternalSkill:
    """A block some tool wrote into Codex's global file, and the upstream skill that replaces it."""
    label: str
    source: str  # <owner>/<repo> on GitHub
    skill: str


# Blocks found between these markers in an old `~/.codex/AGENTS.md`.
KNOWN_BLOCKS = {"<!-- context7 -->": ExternalSkill("Context7", "upstash/context7", "find-docs")}


def config_dir(home: Path) -> Path:
    return home / ".codex"


def plan(home: Path, rules: list, owned: dict, shared_file: Path, os_home: Path, tools=None, rules_path=None):
    """Returns (sections, writes, owned_after) for Codex. MCP tools aren't listed: the
    pre-tool hook matches them by name when they're called."""
    if not shared.harness_found(home, os_home, config_dir(home), PROGRAMS):
        section = Section(f"{LABEL}: memory", config_dir(home) / "config.toml")
        section.changes.append(Change("none", "Codex isn't set up here (no ~/.codex); nothing to turn off"))
        return [section], [], {}
    config_path = config_dir(home) / "config.toml"
    config_old = read_text(config_path)
    md_section, md_writes = _plan_instructions(home, shared_file)
    rules_section, rules_write, owned_rules = _plan_rules(home, rules, owned.get("rules", []))
    config_new, mem_section, mem_writes = _plan_memory(home, config_old or "")
    hook_section, hook_writes, config_new, owned_hooks = _plan_hook(
        home, owned, hook_command(home, os_home, rules_path, NAME), config_new)
    owned_after = {k: v for k, v in (("rules", owned_rules), *owned_hooks.items()) if v}
    config_write = FileWrite(config_path, config_old, config_new if config_new != (config_old or "") else config_old)
    return ([md_section, rules_section, hook_section, mem_section],
            [*md_writes, rules_write, *hook_writes, config_write, *mem_writes], owned_after)


# --- global instructions ----------------------------------------------------------


def _plan_instructions(home: Path, shared_file: Path):
    """`~/.codex/AGENTS.md` becomes a symlink to the shared file, once nothing in it would be lost."""
    path = config_dir(home) / "AGENTS.md"
    section = Section(f"{LABEL}: global instructions", path)
    target = shared_file.resolve()
    override = config_dir(home) / "AGENTS.override.md"
    if (read_text(override) or "").strip():
        section.changes.append(Change(
            "gap", "AGENTS.override.md isn't empty, so Codex reads it instead of AGENTS.md; kept. "
                   "Move its lines into the shared file and empty it"))
    if path.is_symlink() and path.resolve() == target:
        section.changes.append(Change("present", f"link to {shared_file}"))
        return section, []
    old = link_text(Path(os.readlink(path))) if path.is_symlink() else read_text(path)
    text = "" if path.is_symlink() else (old or "")
    rest, blocks = _split_blocks(text)
    writes = []
    for skill in blocks:
        writes += _plan_external_skill(home, skill, section)
    shared_lines = {_bare(l) for l in (read_text(shared_file) or "").splitlines()}
    unmoved = [l.strip() for l in rest.splitlines() if _bare(l) and not l.lstrip().startswith("#")
               and _bare(l) not in shared_lines]
    if unmoved:
        for line in unmoved:
            section.changes.append(Change("extra", _short(line), note="not in the shared file; kept"))
        section.changes.append(Change(
            "gap", f"Codex reads this file, not the shared one, until each of its {len(unmoved)} extra line(s) "
                   "is in the shared file or dropped (references/global-instructions.md, Moving a harness's "
                   "file); the plan links it then"))
        return section, writes
    if old is not None:
        what = "a link elsewhere" if path.is_symlink() else "a file"
        section.changes.append(Change(
            "removed", f"<home>/.codex/AGENTS.md as {what}",
            note="every line is in the shared file or an external skill; kept in the backup"))
    section.changes.append(Change("added", f"link to {shared_file}", note="Codex reads the shared global instructions"))
    return section, [*writes, FileWrite(path, old, link_text(target), link_to=target)]


def _split_blocks(text: str):
    """The text without the known blocks, and the external skills those blocks stand for."""
    found = []
    for marker, skill in KNOWN_BLOCKS.items():
        parts = text.split(marker)
        if len(parts) >= 3:
            text = parts[0] + "".join(parts[2:])
            found.append(skill)
    return text, found


def _plan_external_skill(home: Path, skill: ExternalSkill, section: Section) -> list:
    """Install the upstream skill that replaces a block, globally, the way maintain-environment does."""
    installed = home / ".agents" / "skills" / skill.skill / "SKILL.md"
    if installed.exists():
        section.changes.append(Change(
            "present", f"external skill {skill.skill} from {skill.source}", note=f"replaces the {skill.label} block"))
        return []
    argv = shared.skills_add_argv(home, skill.source, "-s", skill.skill)
    section.changes.append(Change(
        "added", f"external skill {skill.skill} from {skill.source}",
        note=f"replaces the {skill.label} block; apply runs `{' '.join(argv)}`"))
    return [Run(installed, argv, {"HOME": str(home)})]


def _bare(line: str) -> str:
    return re.sub(r"^\s*(?:[-*]|\d+\.)\s+", "", line).strip()


def _short(line: str, width: int = 90) -> str:
    return line if len(line) <= width else line[: width - 1] + "…"


# --- rules --------------------------------------------------------------------------


def patterns_for(rule) -> list:
    """The prefix_rule patterns a command row expands to: an element is a word or a list of
    alternatives. Clustered short flags (`-rf`, `-fr`) share one pattern; separate flags
    get one pattern per order. Shell rows, bare rows and rows on files get none (see gaps_for)."""
    if rule.kind != "command" or _is_shell_row(rule) or rule.bare or rule.flags_only or rule.files:
        return []
    groups = [[_flag(s) for s in g] for g in rule.flags]
    flag_patterns = []
    if groups:
        one_token = [f[0] for f in rule_table.flag_forms(rule) if len(f) == 1]
        if one_token:
            flag_patterns.append([_alts(one_token)])
        if len(groups) > 1:
            flag_patterns += [[_alts(groups[i]) for i in order] for order in itertools.permutations(range(len(groups)))]
    else:
        flag_patterns = [[]]
    operands = rule.operands
    if len(operands) > 1 and all(len(o) == 1 for o in operands):
        operands = [[_alts([o[0] for o in operands])]]  # one-word alternatives share one pattern
    return [[p, *sub, *f, *o] for p in rule.programs for sub in rule.subcommands for f in flag_patterns
            for o in operands]


def _is_shell_row(rule) -> bool:
    return any(p in commands.SHELLS for p in rule.programs)


def _flag(name: str) -> str:
    return f"-{name}" if len(name) == 1 else f"--{name}"


def _alts(words: list):
    return words[0] if len(words) == 1 else list(words)


def render_pattern(pattern: list) -> str:
    return " ".join(w if isinstance(w, str) else "[" + "|".join(w) + "]" for w in pattern)


def justification(rule) -> str:
    """What Codex shows the agent: `<command>` rejected: <this>."""
    instead = "Instead: " if rule.level == "deny" else ""
    return f"{rule.reason} {instead}{rule.instruction} (set-up-machine rule {rule.id})"


def render_rule(pattern: list, rule) -> str:
    return (f"prefix_rule(pattern={json.dumps(pattern, ensure_ascii=False)}, decision=\"{DECISION[rule.level]}\", "
            f"justification={json.dumps(justification(rule), ensure_ascii=False)})")


def parse_rules(text: str) -> list:
    """(pattern, decision) for each prefix_rule in a .rules file. Starlark's call syntax is
    Python's, so the standard library parses it; anything but prefix_rule is skipped."""
    found = []
    for node in ast.walk(ast.parse(text)):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == "prefix_rule":
            kw = {k.arg: k.value for k in node.keywords}
            if "pattern" not in kw:
                continue
            pattern = ast.literal_eval(kw["pattern"])
            decision = ast.literal_eval(kw["decision"]) if "decision" in kw else "allow"
            found.append((pattern, decision))
    return found


def _choices(word) -> set:
    return {word} if isinstance(word, str) else set(word)


def concrete(pattern: list) -> list:
    """Every argv prefix a pattern stands for."""
    return [list(c) for c in itertools.product(*(sorted(_choices(w)) for w in pattern))]


def matches(pattern: list, argv: list) -> bool:
    return len(pattern) <= len(argv) and all(argv[i] in _choices(w) for i, w in enumerate(pattern))


def covers(broad: list, narrow: list) -> bool:
    """Whether every command `narrow` matches is matched by `broad` too."""
    return len(broad) <= len(narrow) and all(_choices(n) <= _choices(b) for b, n in zip(broad, narrow))


def gaps_for(rule) -> list:
    """What gets through once this adapter's rules and the pre-tool hook are in place,
    then the row's own gap, which no harness catches."""
    return _codex_gaps(rule) + ([rule.gap] if rule.gap else [])


def _codex_gaps(rule) -> list:
    if rule.kind == "file":
        how = "reads" if rule.access == "read" else "writes"
        path = rule.paths[0].replace("**/", "").replace("/**", "/…")
        return [f"Codex has no file rules: the pre-tool hook refuses apply_patch edits to these paths, but shell {how} "
                f"(`{'cat ' + path if rule.access == 'read' else 'echo … > ' + path}`) get through, "
                "unless a command row names them"]
    if rule.kind == "mcp-tool":
        return ["Codex's MCP tools aren't listed before a session, so no native entry: the pre-tool hook refuses "
                "matching `mcp__<server>__<tool>` calls when they're made"]
    if rule.flags_only:
        return [f"no Codex rule: prefix rules can't say \"with only flags after it\", so a rule on "
                f"`{rule.programs[0]} -x` would also refuse `{rule.programs[0]} -x NAME=value`; "
                "only the pre-tool hook enforces this row"]
    if rule.bare:
        return [f"no Codex rule: prefix rules can't say \"with nothing after it\", so a rule on "
                f"`{rule.programs[0]}` would also refuse `{rule.programs[0]} …` with arguments; "
                "only the pre-tool hook enforces this row"]
    if rule.files:
        return ["no Codex rule: prefix rules name one literal word in one place, not a path glob anywhere in "
                "the operands; only the pre-tool hook enforces this row, exceptions included"]
    if _is_shell_row(rule):
        return ["no Codex rule: Codex runs every command as `<shell> -lc '…'` (`-c` with login off), so a rule on "
                "`bash -c` would refuse its own wrapper around any command with a redirect or `$(…)`; "
                "only the pre-tool hook enforces this row"]
    if rule.level in ("deny", "allow-and-report"):
        return []  # the pre-tool hook reads every spelling; its misses are one gap in its own section
    through = ["flags after the operands"]
    if any(rule.subcommands):
        through.append(f"options before the subcommand (`{rule.programs[0]} <option> {' '.join(rule.subcommands[0])}`)")
    return ["ask stays native, and prefix rules match the words in order, so these get through: " + "; ".join(through)]


def _names_a_file(rule, pattern: list) -> bool:
    """Whether a rule on the machine, such as `cat .env`, is one case of a command row on files."""
    if len(pattern) < 2 or not all(isinstance(w, str) for w in pattern[:2]) or pattern[0] not in rule.programs:
        return False
    def hit(globs):
        return any(rule_table.glob_regex(g, "/p", "/h").match("/p/" + pattern[1]) for g in globs)
    return hit(rule.files) and not hit(rule.excepts)


def _plan_rules(home: Path, rules: list, owned: list):
    folder = config_dir(home) / "rules"
    path = folder / RULES_FILE
    section = Section(f"{LABEL}: rules", path)
    existing = []
    for other in sorted(folder.glob("*.rules")) if folder.is_dir() else []:
        if other.name == RULES_FILE:
            continue
        try:
            existing += [(p, d, other.name) for p, d in parse_rules(other.read_text())]
        except (SyntaxError, ValueError) as exc:
            section.changes.append(Change("gap", f"couldn't read {other.name} ({exc}); its rules aren't compared"))

    # The generated file holds the whole table, whatever the other files say, so the table's
    # rules and their justifications don't depend on anyone else's file staying as it is.
    old = read_text(path)
    ours = set()
    try:
        ours = {(json.dumps(p), d) for p, d in parse_rules(old or "")}
    except (SyntaxError, ValueError):
        pass  # rewritten below
    lines, desired = [], []
    for rule in rules:
        for gap in gaps_for(rule):
            section.changes.append(Change("gap", gap, rule.level, rule.id))
        if rule.guard:
            section.changes.append(Change(
                "none", f"no semantic guard in Codex for {rule.guard.split(':', 1)[0]}", rule.level, rule.id))
        for pattern in patterns_for(rule):
            desired.append(pattern)
            lines.append(render_rule(pattern, rule))
            text, decision = render_pattern(pattern), DECISION[rule.level]
            want = STRICTNESS[decision]
            found = [max((STRICTNESS.get(d, 0) for p, d, _ in existing if matches(p, c)), default=None)
                     for c in concrete(pattern)]
            if (json.dumps(pattern), decision) in ours:
                section.changes.append(Change("present", text, rule.level, rule.id))
            elif any(f is not None and f < want for f in found):
                section.changes.append(Change("tightened", text, rule.level, rule.id,
                                              f"another rules file is looser; {decision} wins"))
            else:
                section.changes.append(Change("added", text, rule.level, rule.id))
            if all(f is not None and f > want for f in found):
                section.changes.append(Change(
                    "stricter", text, rule.level, rule.id,
                    "another rules file is stricter, and the strictest decision wins; kept, since set-up-machine "
                    f"never loosens. Remove it by hand to get the table's {decision}"))

    on_files = [r for r in rules if r.files]
    for pattern, decision, file in existing:
        if not any(covers(d, pattern) for d in desired) and not any(_names_a_file(r, pattern) for r in on_files):
            section.changes.append(Change("extra", f"{render_pattern(pattern)}: {decision}", note=f"{file}; not in the table; kept"))

    if lines:
        new = RULES_HEADER + "\n" + "\n".join(lines) + "\n"
        return section, FileWrite(path, old, new), [RULES_FILE]
    if old is not None and RULES_FILE in owned:
        section.changes.append(Change("removed", RULES_FILE, note="written by set-up-machine; nothing left in it"))
        return section, FileWrite(path, old, None), []
    return section, FileWrite(path, old, old), []


# --- pre-tool hook ---------------------------------------------------------------------


def trust_hash(command: str, matcher: str = "*", timeout: int = HOOK_TIMEOUT) -> str:
    """The hash Codex records when a PreToolUse command hook is trusted in /hooks: sha256 over
    the canonical JSON of the hook's normalised identity (codex-rs/hooks discovery.rs)."""
    identity = {
        "event_name": "pre_tool_use",
        "matcher": matcher,
        "hooks": [{"type": "command", "command": command, "timeout": timeout, "async": False}],
    }
    text = json.dumps(identity, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return "sha256:" + hashlib.sha256(text.encode()).hexdigest()


def trust_key(hooks_path: Path, group: int, handler: int = 0) -> str:
    return f"{hooks_path}:pre_tool_use:{group}:{handler}"


def _plan_hook(home: Path, owned: dict, wanted: str, config_text: str):
    """Wire the pre-tool hook for every tool in hooks.json, and trust it in config.toml."""
    path = config_dir(home) / "hooks.json"
    section = Section(f"{LABEL}: pre-tool hook", path)
    old = read_text(path)
    try:
        data = json.loads(old) if old is not None else {}
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path} isn't valid JSON ({exc}); fix it by hand, then run the plan again") from exc
    if not isinstance(data, dict) or not isinstance(data.get("hooks", {}), dict):
        raise ValueError(f"{path} must hold a JSON object with a `hooks` object; fix it by hand, then run the plan again")
    groups = [g for g in data.get("hooks", {}).get("PreToolUse", []) if isinstance(g, dict)]
    stale = {c for c in owned.get("hooks", []) if c != wanted}
    present = {h.get("command") for g in groups for h in _handlers(g)}
    new_groups = []
    for g in groups:
        handlers = [h for h in _handlers(g) if h.get("command") not in stale]
        if handlers:
            new_groups.append(g if len(handlers) == len(_handlers(g)) else {**g, "hooks": handlers})
    for command in sorted(stale & present):
        section.changes.append(Change("removed", f"pre-tool hook: {command}",
                                      note="written by set-up-machine; the hook command changed"))
    at = next((i for i, g in enumerate(new_groups) if g.get("matcher") in ("*", "", None)
               and [h.get("command") for h in _handlers(g)] == [wanted]), None)
    if at is None:
        new_groups.append({"matcher": "*", "hooks": [{"type": "command", "command": wanted, "timeout": HOOK_TIMEOUT}]})
        at = len(new_groups) - 1
        section.changes.append(Change(
            "added", f"pre-tool hook: {wanted}",
            note="refuses the table's deny rules however a command is spelled, and reports allow-and-report calls"))
    new = old
    if new_groups != groups:
        data = {**data, "hooks": {**data.get("hooks", {}), "PreToolUse": new_groups}}
        new = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    group = new_groups[at]
    key = trust_key(path, at)
    digest = trust_hash(wanted, group.get("matcher") or "*", group["hooks"][0].get("timeout", HOOK_TIMEOUT))
    config = config_text
    for stale_key in [k for k in owned.get("hook_trust", []) if k != key]:
        config = drop_hook_trust(config, stale_key)
    if hook_trust(config, key) == digest:
        if new == old:
            section.changes.append(Change("wired", f"pre-tool hook wired and trusted for every tool: {wanted}"))
    else:
        config = set_hook_trust(config, key, digest)
        section.changes.append(Change(
            "added", "trust for the pre-tool hook in config.toml",
            note="the hash /hooks records when you trust it; approving this plan is that review"))
    if re.search(r"(?ms)^\s*\[features\][^\[]*^\s*hooks\s*=\s*false", config):
        section.changes.append(Change("gap", "`[features] hooks = false` in config.toml turns every hook off, this one "
                                             "included; set-up-machine leaves it to you"))
    section.changes.append(Change("gap", f"the hook reads every spelling of a command, but can't see {HOOK_MISSES}"))
    section.changes.append(Change(
        "gap", "a trusted project's `.codex/config.toml` can set `[features] hooks = false`, which turns the hook off "
               "there; the rules still hold"))
    return section, [FileWrite(path, old, new)], config, {"hooks": [wanted], "hook_trust": [key]}


def _handlers(group: dict) -> list:
    handlers = group.get("hooks")
    return [h for h in handlers if isinstance(h, dict)] if isinstance(handlers, list) else []


def _state_header(key: str) -> str:
    return f'[hooks.state.{json.dumps(key)}]'


def _state_table(lines: list, key: str):
    """(start, end) line indexes of the key's state table, or None."""
    header = _state_header(key)
    for i, line in enumerate(lines):
        if line.strip() == header:
            end = next((j for j in range(i + 1, len(lines)) if lines[j].lstrip().startswith("[")), len(lines))
            return i, end
    return None


def hook_trust(text: str, key: str):
    lines = text.split("\n")
    span = _state_table(lines, key)
    if span is None:
        return None
    for line in lines[span[0] + 1:span[1]]:
        m = re.match(r'^\s*trusted_hash\s*=\s*"([^"]*)"', line)
        if m:
            return m.group(1)
    return None


def set_hook_trust(text: str, key: str, digest: str) -> str:
    """config.toml with the key's `trusted_hash` set, every other line kept as written."""
    lines = text.split("\n")
    span = _state_table(lines, key)
    entry = f'trusted_hash = "{digest}"'
    if span is None:
        body = text.rstrip("\n")
        return (body + "\n\n" if body else "") + _state_header(key) + "\n" + entry + "\n"
    start, end = span
    for i in range(start + 1, end):
        if re.match(r"^\s*trusted_hash\s*=", lines[i]):
            lines[i] = entry
            return "\n".join(lines)
    lines.insert(start + 1, entry)
    return "\n".join(lines)


def drop_hook_trust(text: str, key: str) -> str:
    lines = text.split("\n")
    span = _state_table(lines, key)
    if span is None:
        return text
    start, end = span
    while end > start + 1 and not lines[end - 1].strip():
        end -= 1
    del lines[start:end]
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lines))


# --- memory -------------------------------------------------------------------------


def _plan_memory(home: Path, config_text: str):
    section = Section(f"{LABEL}: memory", config_dir(home) / "config.toml")
    new, change = set_memories_off(config_text)
    section.changes.append(change)
    section.changes.append(Change(
        "gap", "a trusted project's .codex/config.toml can set memories = true and win over this; "
        "only a system requirements.toml pins it, which the project audit relies on instead",
    ))
    writes = memory.remove_files(home, [config_dir(home) / "memories"], section)
    return new, section, writes


def set_memories_off(text: str):
    """config.toml with `memories = false` in its [features] table, and the change that says so.

    Edits the one line it needs and keeps every other line as written.
    """
    lines = text.split("\n")
    table, features_at = None, None
    for i, line in enumerate(lines):
        if line.lstrip().startswith("[["):
            table = "[[array]]"
            continue
        m = _TABLE.match(line)
        if m:
            table = m.group(1).strip().strip('"')
            if table == "features":
                features_at = i
            continue
        found = (_MEMORIES.match(line) if table == "features" else None) or (_DOTTED.match(line) if table is None else None)
        if found:
            value = found.group(1)
            if value == "false":
                return text, Change("present", "[features] memories = false")
            lines[i] = (line[: line.index("features")] + "features.memories = false") if table is None else FEATURE_LINE
            return "\n".join(lines), Change("tightened", "[features] memories = false", note=f"was {value}")
        if table is None and re.match(r"^\s*features\s*=\s*\{", line):
            raise ValueError("~/.codex/config.toml sets features as an inline table; add memories = false to it by hand")
    if features_at is not None:
        lines.insert(features_at + 1, FEATURE_LINE)
        return "\n".join(lines), Change("added", "[features] memories = false", note="memories off")
    body = text.rstrip("\n")
    return (body + "\n\n" if body else "") + "[features]\n" + FEATURE_LINE + "\n", Change(
        "added", "[features] memories = false", note="memories off")
