"""Cursor adapter: the IDE agent and the `cursor-agent` CLI.

Facts it relies on (see references/cursor.md and docs/research/harness-capabilities.md, section 4):
- Both read `.mdc` user rule files in `~/.cursor/rules/`: the IDE as user rules for every
  project, the CLI by walking up from the working folder, so only for a folder inside the home
  folder. An `.mdc` file applies to every chat only with `alwaysApply: true` frontmatter, so
  the shared file reaches Cursor as a generated copy with that frontmatter, not a link.
- The CLI's permissions are `~/.cursor/cli-config.json`, `permissions.{allow, deny}`.
  `Shell(<prefix>)` matches the prefix and anything after a space; `Shell(<prefix>:)` the
  prefix alone. Globs know only `*`, which matches anything, `/` included, and every other
  character is literal. File rules are `Read(glob)` and `Write(glob)` over absolute paths;
  MCP rules are `Mcp(<server>:<tool>)`, the server being its key in `mcp.json`. There is no ask list.
- The IDE has no user-level deny list: its hard blocks are hooks. `~/.cursor/hooks.json` runs for
  both, and a project can't turn it off. A deny answer's `user_message` is what the CLI shows the agent.
- Cursor has no memory feature (removed in 2.1).
"""
from __future__ import annotations

import copy
import fnmatch
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from .. import rules as rule_table
from ..plan import Change, FileWrite, Section
from ..shared import plan_instructions, read_text
from . import claude_code

NAME = "cursor"
LABEL = "Cursor"

# Rule level -> the cli-config.json list that expresses it; ask has none.
NATIVE_LIST = {"deny": "deny", "allow-and-report": "allow"}
LISTS = ("deny", "allow")
FILE_RULE = {"read": "Read", "write": "Write"}

RULES_FILE = "global-instructions.mdc"
FRONTMATTER = "---\nalwaysApply: true\n---\n"
GENERATED = ("<!-- Generated by set-up-machine from the shared global instructions file, {source}. "
             "Edit that file and run set-up-machine; changes here are overwritten. -->")

# The hook events the pre-tool hook answers, and the matcher each needs (None: every call).
# Shell, MCP and file reads have their own events; writes, deletes and searches come through
# preToolUse, whose MCP calls carry no server name, so they're left to beforeMCPExecution.
HOOK_EVENTS = {
    "beforeShellExecution": None,
    "beforeMCPExecution": None,
    "beforeReadFile": None,
    "preToolUse": "^(Write|Delete|Grep)$",
}
HOOK_TIMEOUT = 10
DISCOVERY_TIMEOUT = 60

_SHELL = re.compile(r"^\s*(Shell|Bash)\s*\((.*)\)\s*$")
_MCP = re.compile(r"^\s*Mcp\s*\((.*)\)\s*$")


def config_dir(home: Path) -> Path:
    return home / ".cursor"


def entries_for(rule, tools=()) -> list:
    if rule.kind == "file":
        # Cursor's globs know only `*`, so an `except` can't be expressed: the plain globs refuse it too.
        return [f"{FILE_RULE[rule.access]}({_cursor_path(p)})" for p in rule.paths]
    if rule.kind == "mcp-tool":
        return [f"Mcp({server}:{tool})" for server, tool in
                (rule_table.split_mcp_name(t) for t in rule_table.matching_tools(rule, tools))]
    if rule.files:
        return []  # Shell rules match text, not the paths in it: the hook covers these
    if rule.bare:
        # `Shell(x:)`: an empty argument pattern matches `x` with nothing after it, and nothing else.
        return [f"Shell({' '.join(prefix)}:)" for prefix in rule_table.command_prefixes(rule)]
    return [f"Shell({' '.join(prefix)})" for prefix in rule_table.command_prefixes(rule)]


def _cursor_path(glob: str) -> str:
    """Cursor matches file rules against absolute paths, so a project-relative glob reaches every folder."""
    return glob if glob.startswith(("~/", "/", "**/")) else "**/" + glob


def covers(existing: str, wanted: str) -> bool:
    """Whether an entry already on the machine matches everything a wanted entry does."""
    if existing == wanted:
        return True
    have, want = _SHELL.match(existing), _SHELL.match(wanted)
    if have and want:
        pattern, text = have.group(2).strip(), want.group(2).strip()
        text = text[:-1] if text.endswith(":") else text  # a bare-command entry
        if ":" in pattern:  # `cmd:args`: covers everything only as a one-word command with `*` arguments
            command, _, args = pattern.partition(":")
            return args.strip() == "*" and " " not in command.strip() and "*" not in command \
                and text.split(" ")[0] == command.strip()
        if pattern.endswith("*") and "*" not in pattern[:-1]:
            return text.startswith(pattern[:-1])  # `*` matches anything, spaces and `/` included
        if "*" in pattern:
            return False
        return text == pattern or text.startswith(pattern + " ")
    have, want = _MCP.match(existing), _MCP.match(wanted)
    if have and want:
        pattern = have.group(1).strip()
        return fnmatch.fnmatchcase(want.group(1).strip(), pattern if ":" in pattern else pattern + ":*")
    return False


def gaps_for(rule) -> list:
    """What gets through once this adapter's entries and the pre-tool hook are in place."""
    gap = rule.gap
    if gap and rule.guard:
        gap += "; Cursor has no semantic guard that covers it (Auto-review skips sandboxable commands and only steers)"
    return _native_gaps(rule) + ([gap] if gap else [])


def _native_gaps(rule) -> list:
    if rule.kind == "file":
        gaps = ["Read and Write rules bind the CLI's file tools, not a shell command (`cat .env`) or a script; "
                "the pre-tool hook checks the file tools in the CLI and the IDE"]
        if rule.excepts:
            gaps.append(f"Cursor's globs know only `*`, so the CLI refuses the exception "
                        f"({', '.join(f'`{e}`' for e in rule.excepts)}) too; the hook leaves it open, and the IDE with it")
        return gaps
    if rule.files:
        return ["Shell rules match the command text, not the paths in it, so this row has no native entry, and the "
                "CLI's Read rules don't bind shell commands: the pre-tool hook alone refuses it"]
    if rule.level == "ask":
        return ["Cursor has no ask level: the CLI prompts only for a command no allow entry covers, never under "
                "`--force`/`--yolo`, and the IDE follows its run mode; the hook leaves ask rows alone"]
    return []


def discover_tools(rules: list):
    """Cursor's MCP tool names, as `mcp__<server>__<tool>`, for the servers a mail row could match.

    Asks `cursor-agent mcp list`, then `mcp list-tools` per matching server, from an empty
    folder so no project's servers count. Returns (names, None) or (None, reason).
    """
    exe = shutil.which("cursor-agent")
    if not exe:
        return None, "the `cursor-agent` command isn't on PATH"
    wanted = [r for r in rules if r.kind == "mcp-tool"]
    with tempfile.TemporaryDirectory() as cwd:
        listed, error = _run(exe, ["mcp", "list"], cwd)
        if error:
            return None, error
        servers = [m.group(1) for m in (re.match(r"^\s*([^\s:]+):\s", _plain(l)) for l in listed.splitlines()) if m]
        names = []
        for server in servers:
            if not any(re.search(r.server, server, re.IGNORECASE) for r in wanted):
                continue
            out, error = _run(exe, ["mcp", "list-tools", server], cwd)
            if error:
                return None, f"couldn't list the tools of MCP server {server}: {error}"
            names += [f"mcp__{server}__{m.group(1)}" for m in
                      (re.match(r"^\s*-\s+(\S+)", _plain(l)) for l in out.splitlines()) if m]
    return sorted(names), None


def _run(exe, args, cwd):
    try:
        proc = subprocess.run([exe, *args], cwd=cwd, capture_output=True, text=True, timeout=DISCOVERY_TIMEOUT)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return "", f"`cursor-agent {' '.join(args)}` failed: {exc}"
    if proc.returncode != 0:
        return "", f"`cursor-agent {' '.join(args)}` exited {proc.returncode}"
    return proc.stdout, None


def _plain(line: str) -> str:
    return re.sub(r"\x1b\[[0-9;]*[A-Za-z]", "", line)


def plan(home: Path, rules: list, owned: dict, shared_file: Path, os_home: Path, tools=None, rules_path=None):
    """Returns (sections, writes, owned_after) for Cursor's IDE and CLI."""
    memory = Section(f"{LABEL}: memory", config_dir(home))
    memory.changes.append(Change("none", "no memory feature in the IDE (removed in 2.1) or the CLI; nothing to turn off"))
    if not config_dir(home).is_dir():
        section = Section(LABEL, config_dir(home))
        section.changes.append(Change("none", "Cursor isn't set up here (no ~/.cursor); nothing to set"))
        return [section, memory], [], {}

    tools_error = None
    if tools is None and any(r.kind == "mcp-tool" for r in rules):
        tools, tools_error = discover_tools(rules)
    perm_section, perm_write, owned_perms = _plan_permissions(
        config_dir(home) / "cli-config.json", rules, owned.get("permissions", {}), tools or [], tools_error)
    hook_section, hook_write, owned_hooks = _plan_hook(
        config_dir(home) / "hooks.json", owned.get("hooks", []),
        claude_code.hook_command(home, os_home, rules_path, harness=NAME))
    md_section, md_write, owned_rules = _plan_instructions(home, rules, shared_file, owned.get("rules_files", []))

    owned_after = {}
    if any(owned_perms.values()):
        owned_after["permissions"] = owned_perms
    if owned_hooks:
        owned_after["hooks"] = owned_hooks
    if owned_rules:
        owned_after["rules_files"] = owned_rules
    return [perm_section, hook_section, memory, md_section], [perm_write, hook_write, md_write], owned_after


def _load_json(path: Path, old):
    try:
        data = json.loads(old) if old is not None else {}
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path} isn't valid JSON ({exc}); fix it by hand, then run the plan again") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{path} must hold a JSON object; fix it by hand, then run the plan again")
    return data


def _plan_permissions(path: Path, rules: list, owned: dict, tools: list, tools_error):
    old = read_text(path)
    config = _load_json(path, old)
    perms = config.get("permissions", {}) if isinstance(config.get("permissions"), dict) else {}
    existing = {name: list(perms.get(name, [])) for name in LISTS}
    section = Section(f"{LABEL} CLI: permissions", path)

    desired, rule_of = {}, {}
    for rule in rules:
        if rule.kind == "mcp-tool":
            section.changes.append(_found(rule, tools, tools_error))
        for gap in gaps_for(rule):
            section.changes.append(Change("gap", gap, rule.level, rule.id))
        level = NATIVE_LIST.get(rule.level)
        if level is None:
            continue
        for entry in entries_for(rule, tools):
            if entry not in desired or LISTS.index(level) < LISTS.index(desired[entry]):
                desired[entry], rule_of[entry] = level, rule.id

    add = {name: [] for name in LISTS}
    covering = set()
    for entry, level in desired.items():
        found = {}
        for name in LISTS:
            hit = next((e for e in existing[name] if covers(e, entry)), None)
            if hit is not None:
                found[name] = hit
        covering.update(found.values())
        if level in found:
            note = "" if found[level] == entry else f"covered by {found[level]}"
            section.changes.append(Change("present", entry, level, rule_of[entry], note))
        elif "deny" in found:  # the table allows it, the machine denies it
            section.changes.append(Change(
                "stricter", entry, level, rule_of[entry],
                f"the machine has {found['deny']} in deny; kept, since set-up-machine never loosens. "
                f"Remove it by hand to get the table's {level}"))
        elif found:
            add[level].append(entry)
            section.changes.append(Change("tightened", entry, level, rule_of[entry], f"was {found['allow']}; deny wins"))
        else:
            add[level].append(entry)
            section.changes.append(Change("added", entry, level, rule_of[entry]))

    remove = {name: [] for name in LISTS}
    owned_after = {name: [] for name in LISTS}
    for name in LISTS:
        for entry in owned.get(name, []):
            if desired.get(entry) == name or (tools_error and entry.startswith("Mcp(")):
                owned_after[name].append(entry)
            elif entry in existing[name]:
                remove[name].append(entry)
                section.changes.append(Change("removed", entry, name, note="written by set-up-machine, no longer in the table"))
        owned_after[name].extend(e for e in add[name] if e not in owned_after[name])

    owned_all = {e for name in LISTS for e in owned.get(name, [])}
    for name in LISTS:
        for entry in existing[name]:
            if entry not in desired and entry not in owned_all and entry not in covering:
                section.changes.append(Change("extra", entry, name, note="not in the table; kept"))

    section.changes.append(Change(
        "gap", "a project's .cursor/cli.json replaces these lists (`\"deny\": []` empties the deny list); "
               "the pre-tool hook, which a project can't turn off, still refuses the deny rows"))
    section.changes.append(Change(
        "gap", "the IDE doesn't read this file and has no deny list of its own: there, the pre-tool hook is the only hard block"))

    new = old
    if any(add.values()) or any(remove.values()) or old is None:
        new_config = copy.deepcopy(config)
        new_config.setdefault("version", 1)
        new_perms = new_config.setdefault("permissions", {})
        for name in LISTS:
            kept = [e for e in new_perms.get(name, []) if e not in remove[name]]
            new_perms[name] = kept + add[name]
        new = json.dumps(new_config, indent=2, ensure_ascii=False) + "\n"
    return section, FileWrite(path, old, new), {k: v for k, v in owned_after.items() if v}


def _found(rule, tools: list, tools_error) -> Change:
    if tools_error:
        return Change("gap", f"couldn't list Cursor's MCP tools: {tools_error}; no native entry, the hook still matches",
                      rule.level, rule.id)
    names = rule_table.matching_tools(rule, tools)
    text = ", ".join(names) if names else "none among the MCP servers in ~/.cursor/mcp.json"
    return Change("found", text, rule.level, rule.id)


def _plan_hook(path: Path, owned: list, wanted: str):
    """Wire the pre-tool hook on each event in HOOK_EVENTS; replace only a hook command this skill wrote."""
    old = read_text(path)
    config = _load_json(path, old)
    section = Section(f"{LABEL}: pre-tool hook", path)
    hooks = config.get("hooks", {})
    if not isinstance(hooks, dict):
        raise ValueError(f"{path}: `hooks` must be a JSON object; fix it by hand, then run the plan again")
    stale = {c for c in owned if c != wanted}

    new_hooks, missing, removed = {}, [], set()
    for event, handlers in hooks.items():
        handlers = handlers if isinstance(handlers, list) else []
        kept = [h for h in handlers if not (isinstance(h, dict) and h.get("command") in stale)]
        removed |= {h.get("command") for h in handlers if isinstance(h, dict) and h.get("command") in stale}
        new_hooks[event] = kept
    for event, matcher in HOOK_EVENTS.items():
        if not any(_is_ours(h, wanted, matcher) for h in new_hooks.get(event, [])):
            handler = {"command": wanted, "timeout": HOOK_TIMEOUT}
            if matcher:
                handler["matcher"] = matcher
            new_hooks.setdefault(event, []).append(handler)
            missing.append(event)

    for command in sorted(removed):
        section.changes.append(Change("removed", f"pre-tool hook: {command}", note="written by set-up-machine; the hook script moved"))
    if missing:
        section.changes.append(Change(
            "added", f"pre-tool hook on {', '.join(missing)}: {wanted}",
            note="refuses the table's deny rules in the IDE and the CLI, and reports allow-and-report calls"))
    else:
        section.changes.append(Change("wired", f"pre-tool hook wired for shell, MCP, file reads and writes: {wanted}"))
    section.changes.append(Change("gap", f"the hook reads every spelling of a command, but can't see {claude_code.HOOK_MISSES}"))
    section.changes.append(Change(
        "gap", "a hook that crashes or times out lets the call through (it isn't `failClosed`, so a broken table "
               "can't stop every call); in the IDE nothing native is left underneath"))

    new = old
    if missing or removed or old is None:
        new_config = copy.deepcopy(config)
        new_config["version"] = new_config.get("version", 1)
        new_config["hooks"] = {e: h for e, h in new_hooks.items() if h or e in hooks}
        new = json.dumps(new_config, indent=2, ensure_ascii=False) + "\n"
    return section, FileWrite(path, old, new), [wanted]


def _is_ours(handler, wanted: str, matcher) -> bool:
    return isinstance(handler, dict) and handler.get("command") == wanted and handler.get("matcher") == matcher


def rules_file_text(shared_text: str, source: str) -> str:
    return FRONTMATTER + GENERATED.format(source=source) + "\n\n" + shared_text


def _plan_instructions(home: Path, rules: list, shared_file: Path, owned: list):
    """A copy of the shared file, as an always-applied user rule in ~/.cursor/rules/."""
    folder = config_dir(home) / "rules"
    path = folder / RULES_FILE
    section = Section(f"{LABEL}: global instructions", path)
    _, shared_write = plan_instructions(home, rules)
    source = "~/" + str(shared_file.relative_to(home)) if shared_file.is_relative_to(home) else str(shared_file)
    want = rules_file_text(shared_write.new, source)
    old = read_text(path)

    for other in sorted(folder.glob("*.mdc")) if folder.is_dir() else []:
        if other.name != RULES_FILE:
            section.changes.append(Change(
                "extra", f"user rule file {other.name}",
                note="kept; move its lines into the shared file, which every harness reads: references/global-instructions.md"))
    section.changes.append(Change(
        "gap", "the CLI reads ~/.cursor/rules only when its working folder is inside the home folder "
               "(it walks up from there); a session elsewhere gets no global instructions"))
    section.changes.append(Change(
        "gap", "account User Rules (Customize > Rules) live on the Cursor account, out of set-up-machine's reach: "
               "lines kept there are invisible to this audit"))

    if old is not None and str(path) not in owned and GENERATED.format(source=source) not in old:
        section.changes.append(Change(
            "gap", f"{RULES_FILE} exists and set-up-machine didn't write it; kept, so Cursor doesn't get the shared file. "
                   "Move its lines into the shared file and delete it"))
        return section, FileWrite(path, old, old), []
    if old == want:
        section.changes.append(Change("present", "copy of the shared file, always applied"))
    else:
        section.changes.append(Change(
            "added", f"copy of the shared file, always applied: {RULES_FILE}",
            note="Cursor can't link or import it; each apply refreshes the copy" if old is None
            else "the copy was out of date; refreshed from the shared file"))
    return section, FileWrite(path, old, want), [str(path)]
