"""The workstation repo, found through the pointer, against the shared file made from it.

The pointer, `~/.config/agents/source.md`, names the person's workstation repo and where
it is cloned, or says there is none:

    - Repository: `<owner>/<repo>`      or      - Repository: none
    - Clone: `<path>`

layout.py names each file the repository holds. Its instructions file holds an optional
`## Working agreement` and `## Glossary`, an `## Environment defaults` table (its Role and
Tool columns are read; any other column is notes) followed by optional `### <tool-name> glossary` subsections, and a
`## Personal workflow` section. The shared global instructions file,
`~/.config/agents/AGENTS.md`, should carry those Tool values (`none` for a role the repository
leaves out), and the text of each other part the repository has and none it lacks. The pointer
itself fills two roles, `workstation-repo` and `path-to-workstation-repo`, as it names them.

Its optional harnesses file can point at a harness's own instructions, for that harness only: the text
under `## Instructions` goes into that harness's own generated file (`HARNESS_FILES`), and
`check_harnesses` compares the two.

Its permissions file holds personal permissions in the rule table's format, which may
also take the level `allow`; `permissions` loads them for the hook and the verify script.
references/workstation.md is the layout for agents; this module only reads it.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from . import layout
from . import rules as rule_table

POINTER = Path(".config/agents/source.md")
SHARED = Path(".config/agents/AGENTS.md")
DEFAULTS = "## Environment defaults"
AGREEMENT = "## Working agreement"
GLOSSARY = "## Glossary"
TOOL_GLOSSARIES = "tool glossaries"  # the `### ` subsections under Environment defaults
WORKFLOW = "## Personal workflow"
WORKFLOW_INTRO = ("Rules for how this person works that pass the team test. "
                  "Anything a project or a skill needs goes there instead.")
POINTER_ROLES = ("workstation-repo", "path-to-workstation-repo")
HARNESS_SECTION = "## Instructions"
# The harnesses set-up-machine can give instructions of their own: the file it writes, and the name it reports.
HARNESS_FILES = {"cursor": (Path(".cursor/rules/harness-instructions.mdc"), "Cursor", Path(".cursor"))}
# The harnesses whose config a reader of its own audits: codex_config.py and pi_config.py.
CONFIG_READERS = ("codex", "pi")
HARNESS_MARK = "<!-- Generated by set-up-machine from the workstation repo's "
REPOSITORY = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")


class PersonalError(ValueError):
    pass


@dataclass(frozen=True)
class Pointer:
    repository: str  # `<owner>/<repo>`, or "" for none
    clone: Path | None
    clone_text: str = ""  # the clone path as the pointer writes it, such as `~/code/setup`


def check(home: Path) -> list:
    """(status, text) lines: `none` or `ok` when the shared file matches the source, else FAIL lines."""
    try:
        pointer = read_pointer(home)
    except PersonalError as exc:
        return [("FAIL", str(exc))]
    if not pointer.repository:
        return [("none", f"no workstation repo (the pointer at {home / POINTER} says none)")]
    instructions_path = layout.instructions(pointer.clone)
    shared_path = home / SHARED
    try:
        tools, workflow, parts = _read_instructions(instructions_path)
        shared = _read(shared_path)
    except PersonalError as exc:
        return [("FAIL", str(exc))]

    fails = []
    from_pointer = dict(zip(POINTER_ROLES, (pointer.repository, pointer.clone_text)))
    for role, value in from_pointer.items():
        if role in tools and tools[role] != value:
            fails.append(f"`{role}` is `{tools[role]}` in {instructions_path}, but the pointer gives `{value}`: "
                         "the pointer fills it, so leave it out of the repository")
    tools = {**tools, **from_pointer}
    shared_tools = _tools(shared)
    if shared_tools is None:
        fails.append(f"{shared_path} has no `{DEFAULTS}` table with Role and Tool columns")
        shared_tools = {}
    for role in tools:
        if role not in shared_tools and shared_tools:
            fails.append(f"`{role}` has no row in {shared_path}, but {instructions_path} gives it `{tools[role]}`")
    for role, value in shared_tools.items():
        want = tools.get(role, "none")
        if value != want:
            fails.append(f"`{role}` is `{value}` in {shared_path}, `{want}` in {instructions_path}")
    shared_workflow = _section(shared, WORKFLOW)
    if shared_workflow is None:
        fails.append(f"{shared_path} has no `{WORKFLOW}` section")
    elif _drop_intro(shared_workflow) != workflow:
        fails.append(f"`{WORKFLOW}` in {shared_path} differs from {instructions_path}")
    for name, got in _optional_parts(shared).items():
        want = parts[name]
        label = "the `### <tool-name> glossary` subsections" if name == TOOL_GLOSSARIES else f"`{name}`"
        if want is None and got is not None:
            fails.append(f"{shared_path} has {label}, which {instructions_path} doesn't")
        elif want is not None and got is None:
            fails.append(f"{shared_path} lacks {label} from {instructions_path}")
        elif want != got:
            fails.append(f"{label} in {shared_path} differs from {instructions_path}")
    if fails:
        return [("FAIL", text) for text in fails]
    lines = len(workflow.splitlines()) if workflow else 0
    carried = [f"{len(tools)} environment defaults"]
    if parts[AGREEMENT] is not None:
        carried.append("the working agreement")
    if parts[GLOSSARY] is not None:
        carried.append("the glossary")
    if parts[TOOL_GLOSSARIES] is not None:
        count = sum(1 for l in parts[TOOL_GLOSSARIES].split("\n") if l.startswith("### "))
        carried.append(f"{count} tool glossar{'y' if count == 1 else 'ies'}")
    carried.append(f"the personal workflow ({lines} lines)")
    return [("ok", f"{pointer.repository} at {pointer.clone}: {', '.join(carried)} match {shared_path}")]


def harness_rule(source: str, path: str) -> str:
    """The text set-up-machine writes for a harness, from its source file's `## Instructions` section.

    path is the source's path relative to the workstation repo's root, as its header names it.
    """
    section = _section(source, HARNESS_SECTION)
    if not section:
        raise PersonalError(f"has no `{HARNESS_SECTION}` section")
    return (f"---\nalwaysApply: true\n---\n{HARNESS_MARK}{path}. Edit that file and run `/set-up-machine`; "
            f"changes here are overwritten. -->\n\n{section}\n")


def check_harnesses(home: Path) -> list:
    """(status, text) lines for each harness's own instructions; none when there is nothing to check.

    `ok` when the generated file matches its source, `FAIL` when it is missing, differs, or outlived
    its source, or when the harnesses file is malformed or points at a missing file, `n/a`
    when the harness isn't set up, and `gap` for a file set-up-machine can't deliver yet or a
    file of the same name someone else wrote.
    """
    try:
        pointer = read_pointer(home)
    except PersonalError:
        return []
    if not pointer.repository:
        return []
    try:
        pointed = layout.harness_files(pointer.clone)
    except layout.LayoutError as exc:
        return [("FAIL", str(exc))]
    lines = []
    for harness, files in pointed.items():
        if "instructions" in files and harness not in HARNESS_FILES:
            lines.append(("gap", f"{harness}: {files['instructions']} has instructions, but set-up-machine "
                                 f"can't deliver them to {harness} yet"))
        if "config" in files and harness not in CONFIG_READERS:
            lines.append(("gap", f"{harness}: {files['config']} is its config, but set-up-machine "
                                 f"can't deliver a config to {harness} yet"))
    for harness, (rel, label, marker) in HARNESS_FILES.items():
        target = home / rel
        written = target.read_text() if target.is_file() else None
        ours = written is not None and HARNESS_MARK in written
        if written is not None and not ours:
            lines.append(("gap", f"{label}: {target} wasn't written by set-up-machine; left alone"))
            continue
        try:
            source = layout.harness_file(pointer.clone, harness, "instructions")
        except layout.LayoutError as exc:
            lines.append(("FAIL", f"{label}: {exc}"))
            continue
        if source is None:
            if ours:
                lines.append(("FAIL", f"{label}: {target} was generated, but {pointer.clone / layout.HARNESSES} "
                                      f"points at no instructions for {harness}; remove it"))
            continue
        if not (home / marker).is_dir():
            lines.append(("n/a", f"{label}: not set up here, so {source} isn't written"))
            continue
        try:
            want = harness_rule(source.read_text(), source.relative_to(pointer.clone).as_posix())
        except PersonalError as exc:
            lines.append(("FAIL", f"{source} {exc}"))
            continue
        if written is None:
            lines.append(("FAIL", f"{label}: {target} doesn't exist; set-up-machine writes it from {source}"))
        elif written != want:
            lines.append(("FAIL", f"{label}: {target} differs from {source}"))
        else:
            lines.append(("ok", f"{label}: {target} matches {source}"))
    return lines


def permissions(home: Path, table: list) -> list:
    """The personal permissions, as Rules, from the repository the pointer names.

    No rows when the pointer is missing, malformed or says none (`check` reports those), or
    when the repository has no permissions file. A malformed row, or one reusing an id of
    the rule table, raises RuleTableError.
    """
    try:
        pointer = read_pointer(home)
    except PersonalError:
        return []
    if not pointer.repository:
        return []
    path = layout.permissions(pointer.clone)
    if not path.is_file():
        return []
    rows = rule_table.load(path, personal=True)
    taken = {r.id for r in table}
    for row in rows:
        if row.id in taken:
            raise rule_table.RuleTableError(f"{path}: the id {row.id!r} is already "
                                            "a row of the rule table")
    return rows


def read_pointer(home: Path) -> Pointer:
    path = home / POINTER
    if not path.is_file():
        raise PersonalError(f"no pointer at {path}: ask the user which repository holds their personal setup, "
                            "or whether they have none, and write it")
    text = path.read_text()
    repository = _field(text, "Repository")
    if repository is None:
        raise PersonalError(f"{path} has no `- Repository:` line")
    if repository.lower() == "none":
        return Pointer("", None)
    if not REPOSITORY.match(repository):
        raise PersonalError(f"{path}: the repository `{repository}` isn't `<owner>/<repo>`")
    clone = _field(text, "Clone")
    if not clone:
        raise PersonalError(f"{path} names {repository} but has no `- Clone:` line")
    if not clone.startswith(("~/", "/")):
        raise PersonalError(f"{path}: the clone path `{clone}` doesn't start with `~/` or `/`")
    clone_path = Path(str(home) + clone[1:]) if clone.startswith("~/") else Path(clone)
    return Pointer(repository, clone_path, clone)


def _field(text: str, name: str):
    m = re.search(rf"^\s*[-*]\s*{name}:\s*(.*?)\s*$", text, re.M)
    return _plain(m.group(1)) if m else None


def _plain(cell: str) -> str:
    cell = cell.strip()
    if len(cell) >= 2 and cell.startswith("`") and cell.endswith("`"):
        cell = cell[1:-1].strip()
    return cell


def _read(path: Path) -> str:
    try:
        return path.read_text()
    except OSError:
        raise PersonalError(f"{path} doesn't exist") from None


def _read_instructions(path: Path):
    text = _read(path)
    tools = _tools(text)
    if tools is None:
        raise PersonalError(f"{path} has no `{DEFAULTS}` table with Role and Tool columns")
    workflow = _section(text, WORKFLOW)
    if workflow is None:
        raise PersonalError(f"{path} has no `{WORKFLOW}` section")
    return {role: value for role, value in tools.items() if value != "none"}, workflow, _optional_parts(text)


def _optional_parts(text: str) -> dict:
    """The working agreement, the glossary and the tool glossaries, each its text or None when absent or empty."""
    parts = {name: _section(text, name) or None for name in (AGREEMENT, GLOSSARY)}
    defaults = (_section(text, DEFAULTS) or "").split("\n")
    start = next((i for i, l in enumerate(defaults) if l.startswith("### ")), None)
    parts[TOOL_GLOSSARIES] = "\n".join(defaults[start:]).strip() or None if start is not None else None
    return parts


def _section(text: str, heading: str):
    """The text under a `## ` heading, up to the next `## ` heading or generated block, stripped."""
    lines = text.split("\n")
    try:
        start = next(i for i, l in enumerate(lines) if l.strip() == heading)
    except StopIteration:
        return None
    body = []
    for line in lines[start + 1:]:
        if line.startswith("## ") or line.startswith("<!-- set-up-machine:"):
            break
        body.append(line)
    return "\n".join(body).strip()


def _drop_intro(body: str) -> str:
    return body[len(WORKFLOW_INTRO):].strip() if body.startswith(WORKFLOW_INTRO) else body


def _tools(text: str):
    """{role: Tool value} from the Environment defaults table, or None without one."""
    body = _section(text, DEFAULTS)
    rows = [_cells(l) for l in (body or "").split("\n") if l.strip().startswith("|")]
    if not rows:
        return None
    header = [_plain(c).lower() for c in rows[0]]
    if "role" not in header or "tool" not in header:
        return None
    role_at, tool_at = header.index("role"), header.index("tool")
    tools = {}
    for row in rows[1:]:
        if all(set(c.strip()) <= set("-: ") for c in row):
            continue  # the separator row
        if len(row) > max(role_at, tool_at):
            tools[_plain(row[role_at])] = _plain(row[tool_at]) or "none"
    return tools


def _cells(line: str) -> list:
    """A table row's cells; a `|` inside backticks or escaped belongs to its cell."""
    cells, cell, code, i = [], "", False, 0
    line = line.strip()
    while i < len(line):
        ch = line[i]
        if ch == "\\" and i + 1 < len(line) and line[i + 1] == "|":
            cell += "|"
            i += 2
            continue
        if ch == "`":
            code = not code
        if ch == "|" and not code:
            cells.append(cell)
            cell = ""
        else:
            cell += ch
        i += 1
    cells.append(cell)
    return cells[1:-1] if len(cells) >= 2 else cells
